### ISSUE TITLE
Error thrown on FitbitDataManager.fetch()

### ISSUE THREAD

**Issue by merdandurmus** [gcappon/fitbitter#1]
The Fitbitter throws an exception on the following code:

              icon: Icon(Icons.device_thermostat),
              iconSize: 50,
              onPressed: () async {
                var startDate = DateTime.now().subtract(Duration(days: 18));
                var endDate = DateTime.now();

                var userId = await FitbitConnector.authorize(
                  context: context,
                  clientID: APIKeys.fitbitClientID,
                  clientSecret: APIKeys.fitbitClientSecret,
                  callbackUrlScheme: APIKeys.fitbitCallbackScheme,
                  redirectUri: APIKeys.fitbitRedirectUri,);

                var fitbitActivityTimeseriesDataManager =
                FitbitActivityTimeseriesDataManager
                (clientID: APIKeys.fitbitClientID,
                clientSecret: APIKeys.fitbitClientSecret,
                    type: "calories",);

                var rawData = await fitbitActivityTimeseriesDataManager.fetch(
                    FitbitActivityTimeseriesAPIURL.dateRangeWithResource(
                  userID: userId,
                  startDate: startDate,
                  endDate: endDate,
                  resource: "calories",),)
                as List<FitbitActivityTimeseriesData>;

                print(rawData);
                //Navigator.pushNamed(context, AllDevices.routeName);
              },
            

The following error is thrown: 
`Failed assertion: line 315 pos 7: 'instanceFactory != null': Object/factory with  type SharedPreferences is not registered inside GetIt. 
(Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
Did you forget to register it?)
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      _GetItImplementation._findFactoryByNameAndType (package:get_it/get_it_impl.dart:315:7)
#3      _GetItImplementation.get (package:get_it/get_it_impl.dart:336:29)
#4      _GetItImplementation.call (package:get_it/get_it_impl.dart:373:12)
#5      new FitbitAuthAPIURL.isTokenValid (package:fitbitter/src/urls/fitbitAuthAPIURL.dart:112:34)
#6      FitbitConnector.isTokenValid (package:fitbitter/src/fitbitConnector.dart:73:40)
#7      FitbitDataManager._checkAccessToken (package:fitbitter/src/managers/fitbit<…>`

Since the code resembles the example on GitHub as much as possible this shouldn't be the case.

**Comment by gcappon** [comment]
Hi, can you please copy and paste your pubspec.yaml file?

**Comment by gcappon** [comment]
Sorry but I can't reproduce the error. The snippet you sent me is working on my device without any problems. If somebody from the community will have the same problem I will reopen the issue.

**Comment by gcappon** [comment]
Currently working on that

**Comment by gcappon** [comment]
@merdandurmus and/or @nayanS95, I just released fitbitter 1.1.1. 
It should fix the problem, can you check that?
Thanks
