### ISSUE TITLE
Error when you don't have data on FitbitCardioScoreData

### ISSUE THREAD

**Issue by Alejandroem** [gcappon/fitbitter#11]
I think this piece of the code might have not been yet moved to null safety, specifically on the file: `fitbitCardioScoreDataManager.dart`

In these lines 

![image](https://user-images.githubusercontent.com/12418734/195335140-d5f22323-a83f-45f0-990c-8734e5b9d0d6.png)

I'm getting the next exception: 

![image](https://user-images.githubusercontent.com/12418734/195335278-c33e2ce9-ffbb-45e9-ba48-5695b96877dc.png)

And I'm aware that I don't have data on this metric on my Fitbit, but the package should also handle that case? I think there might be other instances where this also happens?

**Comment by Alejandroem** [comment]
It also happens when you get `FitbitSpO2Data`

**Comment by gcappon** [comment]
Dear @Alejandroem, thanks for spotting this bug. I will try to solve it ASAP.

**Comment by fraca98** [comment]
> It also happens when you get `FitbitSpO2Data`

I'm also working on this to solve some problems related to `spO2` data and `Heart rate intraday data`. I'll submit a PR as soon as i can

**Comment by gcappon** [comment]
Thank you @fraca98!
I merged the PR, it should fix the issue.
