### ISSUE TITLE
Hard coded scope

### ISSUE THREAD

**Issue by debiotech4ayo** [gcappon/fitbitter#19]
Hello, 

When using the method `FitbitConnector.authorize`, the scope is hard coded in the fitbitAuthAPIURL file. Would it be possible to have it as a parameter so that it can be changed by the user when needed ? Because our app doesn't need all scopes.

Best regards.

**Comment by gcappon** [comment]
Hi, I will surely do it at some point!

**Comment by gcappon** [comment]
Solved in 6250b68 :)

**Comment by debiotech4ayo** [comment]
Thank you ! <3
