### ISSUE TITLE
README update for android developers.

### ISSUE THREAD

**Issue by TessaGush** [gcappon/fitbitter#2]
Hi, hope im not intruding, but I have been trying to use your software for a few days, and have been struggling. I realised that this issue is just for when running on android. 

If you want to run this code on android you need to update your manifest with another activity. 

so in example/android/app/src/main/AndroidManifest.xml 

you add this activity 

<pre><code>&lt;activity android:name="com.linusu.flutter_web_auth.CallbackActivity" &gt;
      &lt;intent-filter android:label="flutter_web_auth"&gt;
        &lt;action android:name="android.intent.action.VIEW" /&gt;
        &lt;category android:name="android.intent.category.DEFAULT" /&gt;
        &lt;category android:name="android.intent.category.BROWSABLE" /&gt;
        &lt;data android:scheme="YOUR_CALLBACK_URL_SCHEME_HERE" /&gt;
      &lt;/intent-filter&gt;
    &lt;/activity&gt;
</code></pre>

in this example you would replace ```YOUR_CALLBACK_URL_SCHEME_HERE``` with ```example```

**Comment by gcappon** [comment]
Thank you very much. I will include that instruction In the example README ASAP!

**Comment by gcappon** [comment]
I updated the example and the  README as suggested. Thank you very much!
