### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by sini25** [gcappon/fitbitter#4]
Hi, im kinda confused in how to use this package actually. Example have one app then lib also have some packages inside. So can u help guide me through on how to start the implementation? 
Second fitbitter is for fitbit web API right?

**Comment by gcappon** [comment]
Hi, please refer to https://gcappon.github.io/fitbitter/getstarted/ to get started with fitbitter and learn how to integrate it within your flutter app, and https://gcappon.github.io/fitbitter/guides/, where you will find useful guides that explain how to fetch specific type of data.
Yes, it is a wrapper of Fitbit Web API.

**Comment by sini25** [comment]
Thank you for the references. I have another issue regarding redirect URL. Once the user allows giving data( by clicking allow button), it should redirect(redirect URL) to the homepage of the example app. Is that how it works? Correct me if I'm wrong. I would like to know how the redirect URL works precisely.
