### ISSUE TITLE
Cant add package

### ISSUE THREAD

**Issue by Diabb05** [gcappon/fitbitter#6]
HI when I add the dependency and try to run my code I get this error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_web_auth:processDebugManifest'.
> Failed to calculate the value of task ':flutter_web_auth:processDebugManifest' property 'packageOverride'.
   > Failed to query the value of property 'applicationId'.
> org.xml.sax.SAXParseException; systemId: file:/C:/Users/user/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.4.1/android/src/main/AndroidManifest.xml; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

I changes the minsdk and added the requires in android manifest

**Comment by gcappon** [comment]
Hi, scraping the net, it seems like you did not edit properly the manifest and the build.gradle file. 
Can you double check?
