### ISSUE TITLE
Web View not closing after successful Authentication

### ISSUE THREAD

**Issue by subhoalmighty** [gcappon/fitbitter#8]
I have successfully integrated Fitbitter and the login and subsequent permission page, the app is redirecting to the redirection url. I am also getting the Authorization Code through Uni Link stream listener.

But everything is happening in background while the web view stays at the top. It never closes and Fitbit.com permission page comes back again. Is there any way to close the WebView after successful authentication. I am on a 7th generation iPad
![unnamed](https://user-images.githubusercontent.com/2297043/171489247-350710f7-f23e-487a-8331-46556ab67d09.png)
.

**Comment by gcappon** [comment]
I think you are not providing a correct redirect Uri.

**Comment by subhoalmighty** [comment]
Actually, what I have found out after thorough inspection is that - the redirection is working fine but in return, it always showing user has cancelled the authentication process. As I was accessing other datas after authentication those processes were showing errors and it seemed like the redirection was not happening.

<img width="797" alt="Screenshot 2022-06-03 at 7 36 41 PM" src="https://user-images.githubusercontent.com/2297043/171870649-72ae82dd-f434-4aa3-80d0-3b8712aff405.png">
.

**Comment by subhoalmighty** [comment]
I have used uni_links: ^0.5.1 to check what links I am getting back. It returns with the correct values
<img width="899" alt="Screenshot 2022-06-03 at 10 23 17 PM" src="https://user-images.githubusercontent.com/2297043/171910588-cf5db6cd-2806-49a2-80f2-8d075e663595.png">
.

**Comment by gcappon** [comment]
Ok, can you copy&paste the piece of code where you are calling Fitbitter.authorize?

**Comment by subhoalmighty** [comment]
`String? userId = await FitbitConnector.authorize(
          context: context,
          clientID: Strings.fitbitClientID,
          clientSecret: Strings.fitbitClientSecret,
          redirectUri: Strings.fitbitRedirectUri,
          callbackUrlScheme: Strings.fitbitCallbackScheme);`

**Comment by gcappon** [comment]
The only other "normal" bug can be that you used wrong ```fitbitRedirectUri``` and ```callBackUrlScheme```. Could you please check this?

**Comment by UvrajSB** [comment]
@subhoalmighty I am facing the same issue, it would be great if you can share the solution if you got any.

**Comment by gcappon** [comment]
Is the browser that you are using (the one that pops up) WebView? Or is it Chrome/Safari?

**Comment by UvrajSB** [comment]
It is webview

**Comment by gcappon** [comment]
That's why you are experiencing the issue! For some reason webview does not close itself. I can assure you that the problem will disappear if you use Chrome.

**Comment by UvrajSB** [comment]
https://user-images.githubusercontent.com/73571511/179423528-b6410df3-f095-482e-9595-9c1cedb1aed2.mp4

See this is the issue I am facing

**Comment by gcappon** [comment]
Ok, the error seems suggesting that you are not setting the right URL SCHEME. Please check your manifest and how you are using the authorize() method.

**Comment by priyak-sdei** [comment]
Any update on this. Facing the same issue.
Android working fine.
In iOS not redirecting to my app

**Comment by gcappon** [comment]
I am closing this since I just run the example app in iOS and Android and it works fine.
